# Setup
title:               Earlout
tagline:             'blog'
description:         Earlout's blog
url:                 http://blog.earlout.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vladyslav Volodin
  url:               http://earlout.com/
  email:             info@earlout.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: earlout-blog
